export const AuditAction = {
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  CLAIM_UPLOADED: "CLAIM_UPLOADED",
  CLAIM_REVIEW_UPDATED: "CLAIM_REVIEW_UPDATED",
  CLAIM_EXTRACTION_RETRY: "CLAIM_EXTRACTION_RETRY",
  EXTRACTION_COMPLETED: "EXTRACTION_COMPLETED",
  EXTRACTION_FAILED: "EXTRACTION_FAILED",
  OCR_CREDITS_DEBITED: "OCR_CREDITS_DEBITED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  DEPARTMENT_CREATED: "DEPARTMENT_CREATED",
  DEPARTMENT_UPDATED: "DEPARTMENT_UPDATED",
  DEPARTMENT_DELETED: "DEPARTMENT_DELETED",
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];

export type AuditResult = "Success" | "Failed" | "Warning";
